# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trj_save_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrjSaveWindow(object):
    def setupUi(self, TrjSaveWindow):
        TrjSaveWindow.setObjectName("TrjSaveWindow")
        TrjSaveWindow.resize(540, 230)
        TrjSaveWindow.setMinimumSize(QtCore.QSize(540, 230))
        TrjSaveWindow.setMaximumSize(QtCore.QSize(540, 230))
        TrjSaveWindow.setStyleSheet("background-color: #191925;")
        self.window_frame = QtWidgets.QFrame(TrjSaveWindow)
        self.window_frame.setGeometry(QtCore.QRect(0, 0, 540, 230))
        self.window_frame.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-color: white;")
        self.window_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_frame.setObjectName("window_frame")
        self.header_frame = QtWidgets.QFrame(self.window_frame)
        self.header_frame.setGeometry(QtCore.QRect(5, 5, 531, 81))
        self.header_frame.setStyleSheet("border-width: 0px;")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.lbl_header = QtWidgets.QLabel(self.header_frame)
        self.lbl_header.setGeometry(QtCore.QRect(0, 5, 531, 65))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_header.setStyleSheet("color: white;")
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.btn_close_window = QtWidgets.QPushButton(self.header_frame)
        self.btn_close_window.setGeometry(QtCore.QRect(499, 1, 31, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_window.sizePolicy().hasHeightForWidth())
        self.btn_close_window.setSizePolicy(sizePolicy)
        self.btn_close_window.setText("")
        self.btn_close_window.setIconSize(QtCore.QSize(32, 32))
        self.btn_close_window.setObjectName("btn_close_window")
        self.path_frame = QtWidgets.QFrame(self.window_frame)
        self.path_frame.setGeometry(QtCore.QRect(10, 80, 522, 66))
        self.path_frame.setStyleSheet("border-width: 0px;")
        self.path_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.path_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.path_frame.setObjectName("path_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.path_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_path_save = QtWidgets.QLabel(self.path_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_path_save.setFont(font)
        self.lbl_path_save.setStyleSheet("color: white;")
        self.lbl_path_save.setObjectName("lbl_path_save")
        self.horizontalLayout_2.addWidget(self.lbl_path_save)
        self.led_path_save = QtWidgets.QLineEdit(self.path_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.led_path_save.setFont(font)
        self.led_path_save.setStyleSheet("background-color: black;\n"
"color: white;\n"
"\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: white;")
        self.led_path_save.setObjectName("led_path_save")
        self.horizontalLayout_2.addWidget(self.led_path_save)
        self.btn_save = QtWidgets.QPushButton(self.window_frame)
        self.btn_save.setGeometry(QtCore.QRect(301, 171, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:13px;\n"
"    border-color: #41416b;\n"
"    min-width: 2em;\n"
"    padding: 6px;\n"
"    color: #41416b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#40ff66;\n"
"     border-width: 4px;\n"
"    border-color:#1c1c1c;\n"
"    color: white;\n"
"}")
        self.btn_save.setObjectName("btn_save")
        self.btn_cancel = QtWidgets.QPushButton(self.window_frame)
        self.btn_cancel.setGeometry(QtCore.QRect(412, 171, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:13px;\n"
"    border-color: #41416b;\n"
"    min-width: 2em;\n"
"    padding: 6px;\n"
"    color: #41416b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#ff4040;\n"
"     border-width: 4px;\n"
"    border-color:#1c1c1c;\n"
"    color: white;\n"
"}")
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(TrjSaveWindow)
        QtCore.QMetaObject.connectSlotsByName(TrjSaveWindow)

    def retranslateUi(self, TrjSaveWindow):
        _translate = QtCore.QCoreApplication.translate
        TrjSaveWindow.setWindowTitle(_translate("TrjSaveWindow", "Form"))
        self.lbl_header.setText(_translate("TrjSaveWindow", "SAVE TRAJECTORY TO FILE:"))
        self.lbl_path_save.setText(_translate("TrjSaveWindow", "Name:"))
        self.btn_save.setAccessibleName(_translate("TrjSaveWindow", "all"))
        self.btn_save.setAccessibleDescription(_translate("TrjSaveWindow", "save"))
        self.btn_save.setText(_translate("TrjSaveWindow", "SAVE"))
        self.btn_cancel.setAccessibleName(_translate("TrjSaveWindow", "all"))
        self.btn_cancel.setAccessibleDescription(_translate("TrjSaveWindow", "cancel"))
        self.btn_cancel.setText(_translate("TrjSaveWindow", "CANCEL"))
