# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trj_upload_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrjUploadWindow(object):
    def setupUi(self, TrjUploadWindow):
        TrjUploadWindow.setObjectName("TrjUploadWindow")
        TrjUploadWindow.resize(540, 495)
        TrjUploadWindow.setMinimumSize(QtCore.QSize(540, 495))
        TrjUploadWindow.setMaximumSize(QtCore.QSize(540, 495))
        TrjUploadWindow.setStyleSheet("background-color:#191929;")
        self.window_frame = QtWidgets.QFrame(TrjUploadWindow)
        self.window_frame.setGeometry(QtCore.QRect(0, 0, 540, 495))
        self.window_frame.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
" border-color: white;")
        self.window_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_frame.setObjectName("window_frame")
        self.btn_cancel = QtWidgets.QPushButton(self.window_frame)
        self.btn_cancel.setGeometry(QtCore.QRect(310, 430, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:13px;\n"
"    border-color: #41416b;\n"
"    min-width: 2em;\n"
"    padding: 6px;\n"
"    color: #41416b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#ff4040;\n"
"     border-width: 4px;\n"
"    border-color:#1c1c1c;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_upload = QtWidgets.QPushButton(self.window_frame)
        self.btn_upload.setGeometry(QtCore.QRect(200, 430, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_upload.setFont(font)
        self.btn_upload.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:13px;\n"
"    border-color: #41416b;\n"
"    min-width: 2em;\n"
"    padding: 6px;\n"
"    color: #41416b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#40ff66;\n"
"     border-width: 4px;\n"
"    border-color:#1c1c1c;\n"
"    color: white;\n"
"}")
        self.btn_upload.setObjectName("btn_upload")
        self.select_frame = QtWidgets.QFrame(self.window_frame)
        self.select_frame.setGeometry(QtCore.QRect(10, 70, 521, 351))
        self.select_frame.setStyleSheet("border-width: 0px;")
        self.select_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_frame.setObjectName("select_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.select_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_select = QtWidgets.QLabel(self.select_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_select.setFont(font)
        self.lbl_select.setStyleSheet("color: white;\n"
"\n"
"")
        self.lbl_select.setObjectName("lbl_select")
        self.verticalLayout.addWidget(self.lbl_select)
        self.lst_select = QtWidgets.QListWidget(self.select_frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lst_select.setFont(font)
        self.lst_select.setStyleSheet("background-color: black;\n"
"color: white;\n"
"")
        self.lst_select.setObjectName("lst_select")
        self.verticalLayout.addWidget(self.lst_select)
        self.header_frame = QtWidgets.QFrame(self.window_frame)
        self.header_frame.setGeometry(QtCore.QRect(4, 4, 532, 60))
        self.header_frame.setStyleSheet("border-width: 0px;")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.lbl_header = QtWidgets.QLabel(self.header_frame)
        self.lbl_header.setGeometry(QtCore.QRect(8, 17, 511, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_header.setFont(font)
        self.lbl_header.setStyleSheet("color: white;\n"
"")
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.btn_close_window = QtWidgets.QPushButton(self.header_frame)
        self.btn_close_window.setGeometry(QtCore.QRect(503, 2, 31, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_window.sizePolicy().hasHeightForWidth())
        self.btn_close_window.setSizePolicy(sizePolicy)
        self.btn_close_window.setText("")
        self.btn_close_window.setIconSize(QtCore.QSize(32, 32))
        self.btn_close_window.setObjectName("btn_close_window")
        self.btn_delete = QtWidgets.QPushButton(self.window_frame)
        self.btn_delete.setGeometry(QtCore.QRect(420, 430, 100, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete.sizePolicy().hasHeightForWidth())
        self.btn_delete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("QPushButton {\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius:13px;\n"
"    border-color: #41416b;\n"
"    min-width: 2em;\n"
"    padding: 6px;\n"
"    color: #41416b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#40ff66;\n"
"     border-width: 4px;\n"
"    border-color:#1c1c1c;\n"
"    color: white;\n"
"}")
        self.btn_delete.setObjectName("btn_delete")

        self.retranslateUi(TrjUploadWindow)
        QtCore.QMetaObject.connectSlotsByName(TrjUploadWindow)

    def retranslateUi(self, TrjUploadWindow):
        _translate = QtCore.QCoreApplication.translate
        TrjUploadWindow.setWindowTitle(_translate("TrjUploadWindow", "Form"))
        self.btn_cancel.setAccessibleName(_translate("TrjUploadWindow", "all"))
        self.btn_cancel.setAccessibleDescription(_translate("TrjUploadWindow", "cancel"))
        self.btn_cancel.setText(_translate("TrjUploadWindow", "CANCEL"))
        self.btn_upload.setAccessibleName(_translate("TrjUploadWindow", "all"))
        self.btn_upload.setAccessibleDescription(_translate("TrjUploadWindow", "upload"))
        self.btn_upload.setText(_translate("TrjUploadWindow", "UPLOAD"))
        self.lbl_select.setText(_translate("TrjUploadWindow", "Select file:"))
        self.lbl_header.setText(_translate("TrjUploadWindow", "UPLOAD TRAJECTORY FROM FILE:"))
        self.btn_delete.setAccessibleName(_translate("TrjUploadWindow", "all"))
        self.btn_delete.setAccessibleDescription(_translate("TrjUploadWindow", "delete"))
        self.btn_delete.setText(_translate("TrjUploadWindow", "DELETE"))
